server:
  port: 10001

spring:
  profiles:
    #env
    active: @env@
  application:
    name: ali-cloud-seata-account
  cloud:
    nacos:
      discovery:
        server-addr: nacos.liulianhaochi.xyz:80
        group: SEATA_GROUP

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: default_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos.liulianhaochi.xyz:80
  config:
    type: nacos
    nacos:
      server-addr: nacos.liulianhaochi.xyz:80
      group: SEATA_GROUP
  service:
    vgroup-mapping:
      default_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info
  config: classpath:logback-@env@.xml

mybatis:
  mapperLocations: classpath:mapper/*.xml