spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_order
    username: root
    password: root
  cloud:
    sentinel:
      transport:
        dashboard: sentinel.liulianhaochi.xyz:80 #配置Sentinel dashboard地址
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: nacos.liulianhaochi.xyz:80
            dataId: ali-cloud-seata-sentinel-pro
            namespace: 0abaaab7-18a0-4d2d-a1f1-fafee3ca14bb
            groupId: SZ_GROUP
            data-type: json
            rule-type: flow