server:
  port: 5001

spring:
  application:
    name: ali-cloud-payment
  cloud:
    nacos:
      discovery:
        server-addr: nacos.liulianhaochi.xyz:80 # 配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'